language: go

go:
  - master

sudo: required

services:
  - docker
  -
git:
  depth: 1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make deploy