language: go
go:
- master
sudo: required
services:
- docker
git:
  depth: 1
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- make deploy
env:
  matrix:
  - secure: oRD0BGXEdvGz6JltdimFuZ6MaYCOBgh6sRrPRb5B1YIOcUCjkHHBrkql3gA2lo6cv2mK1XhY8vwS9emS3BeVp3o7OZpQXrhI+gZeT1OnyFflA1mtqlgG9tRafgwPH7gAReunii5pr1etboI38OslhFfkOLc5XyEs+uZHbCVEF26z7FlcAHRKUApf6LsvfdIOZ4RB7sQYGqLJfqQR3TQuEZY+NHiLmpoBAJ1EtEJbK2NCSolPzV0stXxzCyIdF55JXco7nvDGT5zWk7ryShvImkpA5cWPKrokvaYzA6x12mz0xbtK4HIs1RKNLdk9Bs6MLticNOjLowjSsi6YzrdvtyvdiEa/aSjTQQABBFZlCuzZLnaVEAU9y7naeH43wJtJzmljFykZ9aGRTCxnDAaro0ExNEc2FMNTHoyeAQk0BPWUFYDJc8XwQWOnOoX9ArHcfTMWHx4t4b4VhPPQuPTcuTrsmNPs/4DaRVOg5lRS8UoD1ivQVUl2s69kA1Td51OojPZ3GGyN3rerAEXY337QrzQHfH1/soz9woE3ss89pxRPSFcGiWW+KptY6wecejB5OSsCFA8bMl1dNkavmuoT2ChJOi+FNIndYE28TNZD9bHb1NhLiLKkt52o1QxXlA1fWNMw/6mpWMk6tG3Gw+1qMPiG5rS82lovS4byPvL9ogM=
  - secure: CZ+hcKG7P65CuLCJfEty/mos94ZTMpx7fatYQtxPdiqhzDOtMtfvV+2giHWl9lDFzM6oOmwoCWW+bMdIBhW/zG5NU9tmctevyr5kOlp5k9qTARNWGLS5zn8yF4j7y2/dIsI4XXqyU8WFZXbR4ym+1lPcR/3fJ4GtrccM/kMedruN6E0Tuq6WahGYkg9R2kwi0aZiIXvZ1CoexzBKQG15e0p1NFwoYkmphqCFqY4HqooiVWzKGhYhcm9GX/PIL+UHcJxtlF+18ZKeK7k/Ctxh1NSa3Htk8nh34kmVpB+FeX7MC5JMA8gsiC5xfUVK4w+kR2S3nrEezJMZqLky8JvNjExaMsUMS0/QGDiiJXN1OVQIcisqVdjYS7gVFimYKehSCjB7A4+kKbMhLaREofsV6/be/F8qE+LiMmgfKQOmecA0V6AaZvnYYpVttgJDsrPmcjtsgi2cvE2uq1T9gP+YIFps+JkFZ6h2AoegrsmXvIJciovLDxjws8jhdXaX558yQ0RF5QGN9losA/+aRJbewGs9K9rqAOcl1ZMjLkUWs9LaSJtooumuDWkastPCRmDaP5qCebZeIR6YAPU+3VAUXf7lAET9qlLUDICj7ya5awOy5IKzyoS0GJgwQsZj6XbJpgaSIFBuCMzKB+JgJXCBOs6ZEDSSBPWj3NsM4S/sZ48=
